# Generated by Django 6.0.4 on 2026-05-01 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_status_returnrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='image1',
            new_name='damage_image',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='pickup_status',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='new_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='request_type',
            field=models.CharField(choices=[('return', 'Return'), ('replace', 'Replace')], max_length=10),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
