# Generated by Django 6.0.4 on 2026-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image1_returnrequest_damage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='new_product',
            new_name='replacement_product',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='pickup_tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('picked', 'Picked'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending_pickup', max_length=20),
        ),
    ]
