# Generated by Django 6.0.4 on 2026-05-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_new_product_returnrequest_replacement_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='is_replacement_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('picked', 'Picked'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending_pickup', max_length=20),
        ),
    ]
