# Generated by Django 6.0.4 on 2026-05-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_returnrequest_is_picked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='replacement_product',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
    ]
