# Generated by Django 6.0.4 on 2026-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_returnrequest_replacement_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
