# Generated by Django 6.0.4 on 2026-05-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_userprofile_age_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
