# Generated by Django 6.0.4 on 2026-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_returnrequest_replacement_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
