# Generated by Django 6.0.4 on 2026-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('picked', 'Picked'), ('completed', 'Completed'), ('processed', 'Processed'), ('shipped', 'Shipped'), ('rejected', 'Rejected')], default='pending_pickup', max_length=20),
        ),
    ]
