# Generated by Django 6.0.4 on 2026-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
