# Generated by Django 6.0.4 on 2026-05-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_is_hot_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hot_deal',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
    ]
