# Generated by Django 6.0.4 on 2026-05-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_product_is_hot_deal_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product'),
        ),
    ]
