# Generated by Django 6.0.4 on 2026-05-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_authenticity_product_how_to_use_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannersection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='bannerssection2/')),
                ('link', models.CharField(blank=True, default='/', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
